# Generated by Django 5.2 on 2025-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_comment_id_alter_comment_post_alter_post_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                db_index=True, verbose_name="Дата и время публикации"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="Тег"
            ),
        ),
    ]
